Milestone 1: Enumerable module with several methods
RaminMammadzada/ruby-enumerable-methods pull request #1
Opened 2020-08-12 06:23 UTC by RaminMammadzada

In this project we created an Enumerable module. 
The foowing custom enumerable methods are implemented:
```#my_each``` 
```#my_each_with_index``` 
```#my_select``` 
```#my_all?``` 
```#my_any?``` 
```#my_none?``` 
```#my_count``` 
```#my_map```  
```#my_inject```

At the same time we added #muptiply_els which multiplies all the elements of the array together by using #my_inject .

2020-08-12 19:52 UTC, expjazz requested changes
## Status: Changes Required :recycle: 

Hey Team. You did a Very good job on this project :clap: 

The code is clean, and I can see that you tried to test your code. That is always the correct mentality :1st_place_medal: 

However, there are a few problems (you can check them with detail in the inline comments). Here are the general details:

- [ ] You should handle hashes and ranges.

- [ ] My_each should return self if a block is given, and an enum if no block is given

- [ ] You should handle regex as an argument.

I know this can be tricky, but you really did a great job already :clap: 

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-08-12 19:52 UTC, expjazz commented on enumerable.rb
> +  end
- [ ] This should return an Enum if no block is given
![image](https://user-images.githubusercontent.com/61479648/90058134-b6aae380-dcb7-11ea-9e9c-6b6463019246.png)

- [ ] It should return self if block is given

- [ ] when a block is given and when self is a range, returns the range itself after calling the given block once for each element in self

- [ ] when a block is given and when self is a range, it behaves like #each and calls the given block once for each element in self

- [ ] when a block is given when self is a hash, it behaves like #each and calls the given block once for each element in self

2020-08-12 19:52 UTC, expjazz commented on enumerable.rb
> +
- [ ] This should also return an enumerator if no block is given.

- [ ] It also should return self if the block is given and self is an array

- [ ] when a block is given and  when self is a range, it should return the range itself after calling the given block once for each element in self

- [ ]  when a block is given, and when self is a range, it behaves like #each_with_index calls the given block once for each element in self

2020-08-12 19:52 UTC, expjazz commented on enumerable.rb
> +  end
- [ ] It also needs to return an enumerator if no block is given

2020-08-12 19:52 UTC, expjazz commented on enumerable.rb
> +      return false
- [ ] when a Regex is passed as an argument, it returns true if all of the collection matches the Regex

2020-08-12 19:52 UTC, expjazz commented on enumerable.rb
> +    false
- [ ] when a Regex is passed as an argument, it should return true if any of the collection matches the Regex

2020-08-12 19:52 UTC, expjazz commented on enumerable.rb
> +  end
- [ ] when a Regex is passed as an argument, it should returns false if any of the collection matches the Regex

2020-08-12 19:52 UTC, expjazz commented on enumerable.rb
> +  end
- [ ] It should handle range as well

2020-08-12 19:52 UTC, expjazz commented on enumerable.rb
> +    return self unless block_given?
- [ ] It also should return an enumerator if no block is given

2020-08-12 19:52 UTC, expjazz commented on enumerable.rb
> +        acum = acum.send(arguments[1], item)
- [ ] it is raising a "LocalJumpError" when no block or argument is given

2020-08-13 04:06 UTC, bertil291utn commented
# **Status:** Changes requested 🟠 
<p align="center"> <img src="https://i.cubeupload.com/4HbSFK.jpg" alt="image" width="60" /> <br><strong>Not yet</strong> </p>

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to accomplish as the actual page, you required to do these changes, listed below:
- [ ] Please fix this [requirement](https://github.com/RaminMammadzada/ruby-enumerable-methods/pull/1/files#r469498026) 
  - If you still have issue please check this [one](https://github.com/bertil291utn/enumerabe-methods/blob/development/enumerable_method_asignment.rb)

### Summary

-  Check [Jump Error](https://user-images.githubusercontent.com/24902525/90093013-28068880-dcf0-11ea-8fc9-973e025e905c.png) when no block is given. `#my_inject` method



***

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-08-13 13:19 UTC, RaminMammadzada commented
> # **Status:** Changes requested 🟠
> <img alt="image" width="60" src="https://camo.githubusercontent.com/1ddcf92da200c67b140615f561dd77483e39060c/68747470733a2f2f692e6375626575706c6f61642e636f6d2f34486253464b2e6a7067">
> **Not yet**
> 
> # Hey guys, you've been doing a great job, and also I hope you enjoyed coding.
> ### Your work is amazing you master it GitHub Flow you have a professional README file.
> However, in order to accomplish as the actual page, you required to do these changes, listed below:
> 
> * [ ]  Please fix this [requirement](https://github.com/RaminMammadzada/ruby-enumerable-methods/pull/1/files#r469498026)
>   
>   * If you still have issue please check this [one](https://github.com/bertil291utn/enumerabe-methods/blob/development/enumerable_method_asignment.rb)
> 
> ### Summary
> * Check [Jump Error](https://user-images.githubusercontent.com/24902525/90093013-28068880-dcf0-11ea-8fc9-973e025e905c.png) when no block is given. `#my_inject` method
> 
> Guys work in the requested changes above and request another review.
> Good luck.
> 
> > “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

Please check the previous review. In the last part of expjazz's review he said that  it is raising a "LocalJumpError" when no block or argument is given. Although we that in the original #inject enumerable it gives "LocalJumpError" when NO block or argument is given. So who should we follow ?

2020-08-13 13:20 UTC, bertil291utn requested changes
# **Status:** Changes requested 🟠 
<p align="center"> <img src="https://i.cubeupload.com/4HbSFK.jpg" alt="image" width="60" /> <br><strong>Not yet</strong> </p>

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to accomplish as the actual page, you required to do these changes, listed below:
- [ ] Please fix this [requirement](https://github.com/RaminMammadzada/ruby-enumerable-methods/pull/1/files#r469498026) 
  - If you still have issue please check this [one](https://github.com/bertil291utn/enumerabe-methods/blob/development/enumerable_method_asignment.rb)

### Summary
- Please you have to make changes before sending for a review 
-  Check [Jump Error](https://user-images.githubusercontent.com/24902525/90093013-28068880-dcf0-11ea-8fc9-973e025e905c.png) when no block is given. `#my_inject` method



***

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-08-13 21:03 UTC, krys2fa commented
# Status: Project Approved! 🥇 
Congratulations @RaminMammadzada and @mateomh! 
You made all the requested changes and got the project approved. 👍 

Your hard work has really paid off. You can now merge this branch into the master branch and go on with your next project.

💡  Do not forget to submit your project completion form after merging this branch.

All the best team,
Chris

2020-08-13 21:54 UTC, merged